package one.digitalinnovation.persoalapi.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.time.LocalDate;
import java.util.List;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Entity
public class Person {

    //id
    @Id
    //autoincrement value autogenerated index id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    @Column(nullable = false)
    private String firstname;

    @Column(nullable = false)
    private String lastName;

    // valor obrigatorio e unico
    @Column(nullable = false, unique = true)
    private String cpf;

    private LocalDate birthday;


    @OneToMany(fetch = FetchType.LAZY, cascade = {CascadeType.PERSIST})
    private List<Phone> phones;
}
